name: Build

on:
  push: { }
  workflow_dispatch: { }

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.0.2

      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install toolchain
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 16
          msbuild-architecture: x86

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: models
          path: ${{ github.workspace}}/build/components/589*/${{ env.BUILD_TYPE }}/i3000-components-589*.dll
