name: Check

on:
  pull_request: { }

jobs:
  editorconfig:
    runs-on: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Install EditorConfig
        # note: `v1.0.0` does not support Windows
        uses: editorconfig-checker/action-editorconfig-checker@d4fca16fc71adef10fbe101903b654449fa9570c
      - name: Run EditorConfig
        run: editorconfig-checker
