name: Check

on:
  pull_request: { }

jobs:
  editorconfig:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
